---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  data_bags_path: "test/fixtures/data_bags"

platforms:
  - name: ubuntu-10.04
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: omnios-r151006c
    driver:
      box: omnios-r151006c
      box_url: http://omnios.omniti.com/media/OmniOS_r151006c-r1.box

suites:
  - name: client
    run_list:
      - recipe[chef-splunk::default]
      - recipe[test::default]
    attributes:
      dev_mode: true
      splunk:
        accept_license: true
        tcpout_server_config_map:
          sslCommonNameToCheck: sslCommonName
          sslCertPath: $SPLUNK_HOME/etc/certs/cert.pem
          sslPassword: password
          sslRootCAPath: $SPLUNK_HOME/etc/certs/cacert.pem
          sslVerifyServerCert: false
        input:
          host: localhost
          ports:
            - port_num: 123123
              config:
                connection_host: dns
                sourcetype: syslog
                souce: tcp:123123

  - name: server
    run_list:
      - recipe[chef-splunk::default]
    attributes:
      dev_mode: true
      splunk:
        is_server: true
        accept_license: true
        ssl_options:
          enable_ssl: true

  - name: disabled
    run_list:
      - recipe[chef-splunk::default]
    attributes:
      splunk:
        disabled: true

  - name: upgrade_client
    run_list:
      - recipe[chef-splunk::default]
      - recipe[chef-splunk::upgrade]
    attributes:
      dev_mode: true
      splunk:
        accept_license: true
        upgrade_enabled: true

  - name: upgrade_server
    run_list:
      - recipe[chef-splunk::default]
      - recipe[chef-splunk::upgrade]
    attributes:
      dev_mode: true
      splunk:
        accept_license: true
        upgrade_enabled: true
        is_server: true
