# rubocop todo:
#
Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'test/integration/client_lwrps/serverspec/splunkapp_spec.rb'
    - 'test/integration/server_lwrps/serverspec/splunkapp_spec.rb'
    - 'test/integration/client-inputs-outputs/serverspec/client_spec.rb'

AlignParameters:
  Enabled: false
ClassLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
PerceivedComplexity:
  Enabled: false
SpaceBeforeFirstArg:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/FileName:
  Enabled: false
